<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>python on Rajat Mhetre</title>
    <link>http://mhetrerajat.github.io/tags/python/</link>
    <description>Recent content in python on Rajat Mhetre</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    <lastBuildDate>Wed, 11 Jan 2017 00:00:00 +0000</lastBuildDate><atom:link href="http://mhetrerajat.github.io/tags/python/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>Default Arguments in Python</title>
      <link>http://mhetrerajat.github.io/posts/default-arguments-in-python/</link>
      <pubDate>Wed, 11 Jan 2017 00:00:00 +0000</pubDate>
      
      <guid>http://mhetrerajat.github.io/posts/default-arguments-in-python/</guid>
      <description>Pythonâ€™s handling of default argument values is one of the few things that tends to create mistakes unknowingly (only once though).
This horror story is from my personal experience. It took me an hour to debug my silly mistake of using mutable value as default argument in function. Its really difficult to find this type bugs in thousands of lines of code.
Using Mutable Value as function argument def foo(numbers=[]): numbers.</description>
    </item>
    
  </channel>
</rss>
